experiment_name: dsbench-rl
trial_name: trial0
seed: 1
tokenizer_path: ${actor.path}

cluster:
  n_nodes: 1
  n_gpus_per_node: 4
  fileroot: /home/rxl210009/MLAgent_AReaL/experiments
  name_resolve:
    type: nfs
    nfs_record_root: /home/rxl210009/MLAgent_AReaL/name_resolve

allocation_mode: vllm:d2p1t1+d2p1t1

saver:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1

recover:
  mode: disabled
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}

stats_logger:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  wandb:
    mode: disabled

export_style: concat
agent_run_args:
  max_turns: 3

rollout:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  max_concurrent_rollouts: 64
  consumer_batch_size: ${train_dataset.batch_size}
  max_head_offpolicyness: 2
  tokenizer_path: ${tokenizer_path}
  dump_to_file: true
  fileroot: ${cluster.fileroot}
  scheduling_spec: ${actor.scheduling_spec}

gconfig:
  n_samples: 4
  max_new_tokens: 1024
  temperature: 0.6

actor:
  path: Qwen/Qwen2.5-3B-Instruct
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  dtype: bfloat16
  optimizer:
    type: adam
    lr: 1.70e-5
  reward_norm:
    mean_level: group
    std_level: group
    group_size: ${gconfig.n_samples}
  scheduling_spec:
    - task_type: worker
      port_count: 2
      gpu: 1
      cpu: 4
      mem: 32
      cmd: python3 -m areal.scheduler.rpc.rpc_server

ref:
  path: ${actor.path}
  dtype: ${actor.dtype}
  scheduling_strategy:
    type: colocation
    target: actor

vllm:
  model: ${actor.path}
  seed: ${seed}
  skip_tokenizer_init: false
  dtype: ${actor.dtype}
  max_model_len: 8192
  gpu_memory_utilization: 0.7

train_dataset:
  path: /home/rxl210009/MLAgent_AReaL/data/dsbench_modeling # 包含 dsbench 关键字
  type: rl
  batch_size: 1
  max_length: 4096

valid_dataset:
  path: /home/rxl210009/MLAgent_AReaL/data/dsbench_modeling
  type: rl
  batch_size: 1
